- name: Install dependencies
  dnf:
    name:
      - policycoreutils-python-utils
      - openssh-server
      - openssh-clients
      - perl
    state: present

- name: Enable and start sshd service
  systemd:
    name: sshd
    enabled: yes
    state: started

- name: Add GitLab repo
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
    dest: /tmp/script.rpm.sh
    mode: '0755'

- name: Run GitLab repo script
  command: /tmp/script.rpm.sh
  args:
    creates: /etc/yum.repos.d/gitlab_gitlab-ce.repo

- name: Install gitlab-ce
  dnf:
    name: gitlab-ce
    state: present

- name: Ensure /etc/gitlab/ssl directory exists
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate private key
  command: >
    openssl genrsa -out /etc/gitlab/ssl/gitlab.{{ internal_domain }}.key 4096
  args:
    creates: /etc/gitlab/ssl/gitlab.{{ internal_domain }}.key

- name: Generate self-signed certificate
  command: >
    openssl req -x509 -new -nodes -sha512 -days 3650
    -subj "/C=KR/ST=Seoul/L=Seoul/O=Chanandy/OU=Personal/CN=gitlab.{{ internal_domain }}"
    -key /etc/gitlab/ssl/gitlab.{{ internal_domain }}.key
    -out /etc/gitlab/ssl/gitlab.{{ internal_domain }}.crt
  args:
    creates: /etc/gitlab/ssl/gitlab.{{ internal_domain }}.crt

- name: Fetch the certificate file from remote host
  fetch:
    src: /etc/gitlab/ssl/gitlab.{{ internal_domain }}.crt   # 원격 서버 파일 경로
    dest: /etc/ssl/private/                                 # 로컬 저장 경로 (디렉토리)
    flat: yes                                      # true면 dest를 디렉토리로 안보고 파일명까지 포함해서 저장

- name: Set external_url in gitlab.rb
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: '^#?external_url\s*=.*'
    line: "external_url 'https://gitlab.chanandy.store'"
    create: yes

- name: Enable nginx
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^#?nginx\\['enable'\\]\\s*=.*"
    line: "nginx['enable'] = true"
    create: yes

- name: Enable redirect HTTP to HTTPS
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^#?nginx\\['redirect_http_to_https'\\]\\s*=.*"
    line: "nginx['redirect_http_to_https'] = true"
    create: yes

- name: Set redirect HTTP to HTTPS port
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^#?nginx\\['redirect_http_to_https_port'\\]\\s*=.*"
    line: "nginx['redirect_http_to_https_port'] = 80"
    create: yes

- name: Set ssl_certificate
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^#?nginx\\['ssl_certificate'\\]\\s*=.*"
    line: "nginx['ssl_certificate'] = \"/root/gitlab_certs/gitlab.{{ internal_domain }}.crt\""
    create: yes

- name: Set ssl_certificate_key
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^#?nginx\\['ssl_certificate_key'\\]\\s*=.*"
    line: "nginx['ssl_certificate_key'] = \"/root/gitlab_certs/gitlab.{{ internal_domain }}.key\""
    create: yes

- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure