- name: Install dependencies
  dnf:
    name:
      - policycoreutils-python-utils
      - openssh-server
      - openssh-clients
      - perl
    state: present

- name: Enable and start sshd service
  systemd:
    name: sshd
    enabled: yes
    state: started

- name: Add GitLab repo
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
    dest: /tmp/script.rpm.sh
    mode: '0755'

- name: Run GitLab repo script
  command: /tmp/script.rpm.sh
  args:
    creates: /etc/yum.repos.d/gitlab_gitlab-ce.repo

- name: Install gitlab-ce
  dnf:
    name: gitlab-ce
    state: present

- name: Ensure /etc/gitlab/ssl directory exists
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate private key
  command: >
    openssl genrsa -out /etc/gitlab/ssl/gitlab.{{ internal_domain }}.key 4096
  args:
    creates: /etc/gitlab/ssl/gitlab.{{ internal_domain }}.key

- name: Generate self-signed certificate
  command: >
    openssl req -x509 -new -nodes -sha512 -days 3650
    -subj "/C=KR/ST=Seoul/L=Seoul/O=Chanandy/OU=Personal/CN=gitlab.{{ internal_domain }}"
    -key /etc/gitlab/ssl/gitlab.{{ internal_domain }}.key
    -out /etc/gitlab/ssl/gitlab.{{ internal_domain }}.crt
  args:
    creates: /etc/gitlab/ssl/gitlab.{{ internal_domain }}.crt

- name: Fetch the certificate file from remote host
  fetch:
    src: /etc/gitlab/ssl/gitlab.{{ internal_domain }}.crt   # 원격 서버 파일 경로
    dest: /etc/ssl/private/                                 # 로컬 저장 경로 (디렉토리)
    flat: yes                                      # true면 dest를 디렉토리로 안보고 파일명까지 포함해서 저장

- name: Generate /etc/gitlab/gitlab.rb from template
  template:
    src: ../files/gitlab.rb.template.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: '0644'
  diff: yes


- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure