- name : setup init
  hosts: all
  become: true
  roles:
    - setup_init

- name: Install Jenkins
  hosts: jenkins_controller
  become: true
  vars_files:
    - vars.yml
  roles:
    - jenkins
- name: Web Server
  hosts: web
  become: true
  vars_files:
    - vars.yml
  roles:
    - web
