---
- name: Ensure /etc/letsencrypt exists
  file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy fullchain.pem
  copy:
    src: /home/ec2-user/letsencrypt/fullchain.pem
    dest: /etc/letsencrypt/fullchain.pem
    owner: root
    group: root
    mode: '0644'
    remote_src: true

- name: Copy privkey.pem
  copy:
    src: /home/ec2-user/letsencrypt/privkey.pem
    dest: /etc/letsencrypt/privkey.pem
    owner: root
    group: root
    mode: '0600'
    remote_src: true
- name: Install nginx
  dnf:
    name: nginx
    state: present

- name: Enable nginx
  systemd:
    name: nginx
    enabled: true

- name: Start nginx
  systemd:
    name: nginx
    state: started

- name: Copy nginx config for chanandy.store
  template:
    src: ../files/chanandy.store.conf.j2
    dest: /etc/nginx/conf.d/chanandy.store.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Test nginx configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: nginx_test.rc != 0
